name: Bug
description: Something's broken.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: expected
    attributes:
      label: What should happen
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What happens instead
      description: Paste the error if there is one.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      value: |
        1. 
        2. 
    validations:
      required: true
