name: Task
description: Something that needs doing.
title: "[Task]: "
labels: ["task"]
body:
  - type: textarea
    id: what
    attributes:
      label: What needs doing
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Done when
      value: |
        - [ ] 
    validations:
      required: true
  - type: dropdown
    id: deliverable
    attributes:
      label: Deliverable
      options: ["P0", "P1", "P2", "P3", "P4", "P5", "N/A"]
    validations:
      required: true
